minor windows fixes
open-goal/jak-project pull request #1311
Opened 2022-04-16 22:22 UTC by ManDude

- removes unintentional copy-constructors in some places. this didn't really improve speed at all (for me) but it did reduce the binary size slightly. also, less things visual studio complains at me about.
- `define` now keeps the name of the thing it's defining on the same line instead of breaking.
- hopefully really forces AVX compilation on clang-cl.
- decompiler tool has a timer now.

2022-04-17 00:05 UTC, water111 approved these changes
looks good, other than the test failure

2022-04-17 00:05 UTC, water111 commented on decompiler/IR2/FormExpressionAnalysis.cpp
> +    auto& lab = env.file->labels.at(arg.label());
can you make these `const auto&`s? Just in case some of this code used to modify the copy and would cause problems if it modified the original?

2022-04-17 21:45 UTC, water111 requested changes
I only checked some, but do we really want to make all of these changes? Stuff like Object and register are very fast to copy and it's very easy to add a bug like taking a reference to something in a container that gets resized.

2022-04-17 21:45 UTC, water111 commented on decompiler/IR2/AtomicOp.cpp
> +    for (auto& x : m_branch_delay->read_regs()) {
the `Register` class is just a `u16` so it's not a problem to copy these.

2022-04-17 21:45 UTC, water111 commented on test/test_reader.cpp
> +  auto& result = reader.read_from_file({"test", "test_data", "test_reader_file0.gc"})
This one isn't safe to be a reference - the reader returns an `Object` by value.

2022-04-17 21:45 UTC, water111 commented on test/test_pretty_print.cpp
> +  auto& obj =
also not safe to be a reference

2022-04-17 21:45 UTC, water111 commented on test/test_pretty_print.cpp
> +  auto& gcommon_code2 = pretty_print::get_pretty_printer_reader()
also not safe to be a reference

2022-04-17 21:45 UTC, water111 commented on test/test_pretty_print.cpp
> +  auto& obj = pretty_print::get_pretty_printer_reader()
also not safe to be a reference

2022-04-17 21:45 UTC, water111 commented on test/test_pretty_print.cpp
> +  auto& gcommon_code2 = pretty_print::get_pretty_printer_reader()
also not safe to be a reference

2022-04-17 21:45 UTC, water111 commented on test/test_pretty_print.cpp
> +  auto& gcommon_code2 = pretty_print::get_pretty_printer_reader()
also not safe to be a reference

2022-04-17 21:45 UTC, water111 commented on test/test_pretty_print.cpp
> +  auto& body = pretty_print::get_pretty_printer_reader().read_from_string(str).as_pair()->cdr;
also not safe to be a reference

2022-04-17 21:45 UTC, water111 commented on test/decompiler/test_DataParser.cpp
> +    auto& actual_form =
not safe to be a reference

2022-04-17 21:45 UTC, water111 commented on test/decompiler/test_DataParser.cpp
> +    auto& expected_form =
not safe to be a reference

2022-04-17 21:45 UTC, water111 commented on test/goalc/test_with_game.cpp
> +  auto& di = shared_compiler->compiler.get_debugger().get_debug_info_for_object("gcommon");
make `const`

2022-04-17 21:45 UTC, water111 commented on test/goalc/test_with_game.cpp
> +  auto& lookup_2 = mem_map.lookup(gk_main.start_addr + 12);
`const`

2022-04-17 21:45 UTC, water111 commented on test/decompiler/FormRegressionTest.cpp
> +  auto& expected_form =
not safe to be reference

2022-04-17 21:45 UTC, water111 commented on test/decompiler/FormRegressionTest.cpp
> +  auto& actual_form =
not safe

2022-04-17 21:45 UTC, water111 commented on test/decompiler/FormRegressionTest.cpp
> +  auto& expected_form =
not safe

2022-04-17 21:45 UTC, water111 commented on test/decompiler/FormRegressionTest.cpp
> +  auto& actual_form =
not safe

2022-04-17 21:45 UTC, water111 commented on goalc/regalloc/Allocator_v2.cpp
> +  for (auto& sr : emitter::gRegInfo.get_all_saved()) {
likely faster if it's not a reference

2022-04-17 21:45 UTC, water111 commented on goalc/regalloc/Allocator_v2.cpp
> +    for (auto& reg : order) {
likely faster if its not a reference

2022-04-17 21:45 UTC, water111 commented on goalc/regalloc/Allocator_v2.cpp
> +  for (auto& lr : live_ranges) {
likely faster if not a reference

2022-04-17 21:45 UTC, water111 commented on goalc/regalloc/Allocator.cpp
> +  for (auto& sr : emitter::gRegInfo.get_all_saved()) {
likely faster if not a reference

2022-04-17 21:45 UTC, water111 commented on goalc/regalloc/Allocator.cpp
> +    for (auto& reg : reg_order) {
likely faster if not a reference

2022-04-17 21:45 UTC, water111 commented on goalc/regalloc/Allocator.cpp
> +  for (auto& exclusive : in.instructions.at(idx).exclude) {
likely faster if not a reference

2022-04-17 21:45 UTC, water111 commented on goalc/compiler/compilation/Type.cpp
> +  auto& type = pair_car(*rest);
`const`

2022-04-17 21:45 UTC, water111 commented on goalc/compiler/compilation/Type.cpp
> +    auto& count_obj = pair_car(*rest);
`const`

2022-04-17 21:45 UTC, water111 commented on goalc/compiler/compilation/Type.cpp
> +    auto& count_obj = pair_car(*rest);
`const`

2022-04-17 21:45 UTC, water111 commented on goalc/compiler/compilation/Type.cpp
> +    auto& field_obj = pair_car(*rest);
`const`

2022-04-17 23:23 UTC, ManDude commented
Probably not, I was just wondering what would happen if I did. I *maybe* got a slight speed increase in the compiler (`(mi)` went from no faster than 25s to no faster than 23s), but if it leads to more bugs then I don't really care about that.

2022-04-18 01:11 UTC, water111 approved these changes
Looks good, thanks!

"minor" windows fixes:
![image](https://user-images.githubusercontent.com/48171810/163739637-aeb01fb5-8201-4766-b43e-cb344dbf0c7c.png)

2022-04-18 01:11 UTC, merged