use normal/inverted and add option to restore original jak 1 defaults
open-goal/jak-project pull request #1361
Opened 2022-05-19 01:16 UTC by dallmeyer

This reverts back to using "Inverted" instead of "Flipped" terminology for camera controls (and adjusts the related code accordingly). In order to avoid confusing players who are used to most of these controls being inverted in the original Jak game, it defaults to the original controls and I also added an option to restore these controls:
- first-person horizontal: NOT inverted
- first-person vertical: inverted
- third person horizontal: inverted
- third-person vertical: inverted

@ManDude I think this is more in line with what you were thinking?

Below video shows the default Jak 1 values, then I toggle them all and use the "Restore Original Game Controls" option to reset  (it's a little hard to tell I select that option in the video since there's no immediate change on the UI until you cycle back through the options - maybe this should exit the menu or give some kind of confirmation?)

https://user-images.githubusercontent.com/2515356/169180671-00a57c1e-3bbc-4cb4-9467-26657ef03f05.mp4

2022-05-19 21:03 UTC, ManDude approved these changes
Looks fine to me.

2022-05-19 21:03 UTC, ManDude commented on decompiler/config/all-types.gc
> +  (camera-controls-original     #x1007)
Good thing I future proofed some of these IDs!

2022-05-21 19:48 UTC, water111 commented
Everything looks good to me, but there's a merge conflict. If you can fix that, I'll merge this.

2022-05-23 09:18 UTC, ManDude requested changes
Looks good but I just want some code to be cleaned up, and some sound effects for UX!

2022-05-23 09:18 UTC, ManDude commented on goal_src/pc/progress-pc.gc
> +                  (reset-original-camera *pc-settings*)
Add a `(sound-play-by-name (static-sound-name "cursor-options") (new-sound-id) 1024 0 0 1 #t)` so there's an audio confirmation when you select the option. This should (but I'm not sure) correspond to that "ding" sound.

2022-05-23 18:08 UTC, dallmeyer commented on goal_src/engine/camera/cam-states.gc
> +    )
Ah okay I noticed the refactoring but wasn't sure the motivation behind it - makes sense, will update

2022-05-23 19:56 UTC, merged