Italian subtitles (WIP)
open-goal/jak-project pull request #1568
Opened 2022-06-28 00:27 UTC by manuelx98

Draft until all the english subtitles are finished.
Many things still in WIP and everything is subject to change.

TODO:

* [x]  intro
* [x]  sidekick
* [x]  oracle
* [x]  training
* [x]  village1
* [x]  beach
* [x]  jungle
* [x]  misty
* [x]  firecanyon
* [x]  village2
* [x]  swamp
* [x]  rolling
* [x]  sunken
* [x]  ogre
* [x]  village3
* [x]  snowy
* [x]  spidercave
* [x]  lavatube
* [x]  citadel
* [x]  finalboss
_____________
* [x]  default
_____________
* [x]  timings
* [x]  game_text_it.gs

2022-09-21 17:51 UTC, Max-feded commented
Buonasera, vorrei aiutare con le traduzioni, come posso fare?

2022-09-21 19:43 UTC, manuelx98 commented
> Buonasera, vorrei aiutare con le traduzioni, come posso fare?

Abbiamo un gruppo Telegram, puoi scrivermi il tuo contatto Discord o Telegram che ti mando l'invito?

2022-09-21 21:05 UTC, Max-feded commented
> > Buonasera, vorrei aiutare con le traduzioni, come posso fare?
> 
> Abbiamo un gruppo Telegram, puoi scrivermi il tuo contatto Discord o Telegram che ti mando l'invito?

Ciao, ti do i miei 2 contatti, preferirei discord come metodo di comunicazione.

Telegram: @Federico_IT
Discord: Federico IT#2745

2022-10-14 19:53 UTC, Milo721 commented
Buonasera, vorrei contribuire anche io se possibile

2022-10-15 15:59 UTC, manuelx98 commented
> Buonasera, vorrei contribuire anche io se possibile.
> Io ho tradotto e completato il file game_text_it.gs

Volentieri, mandami un contatto e ti aggiungo al gruppo.

2022-10-15 18:56 UTC, Milo721 commented
Telegram: @Mirito721

2023-02-22 21:10 UTC, ManDude commented
It looks like (basically) all of the text is there. If you guys want, you can merge from `master`, fix the conflicts and we can add it to the game. If you wanna make small adjustments or fixes, you can open another PR for it.

2023-03-31 19:35 UTC, ManDude requested changes
Looks good, aside from some things I pointed out.

2023-03-31 19:35 UTC, ManDude commented on game/assets/jak1/text/game_text_en.gs
> +        "ITALIAN")
Not needed.

2023-03-31 19:35 UTC, ManDude commented on game/assets/jak1/text/game_text_it.gs
> +  )
Not needed.

2023-03-31 19:35 UTC, ManDude commented on game/assets/jak1/text/game_text_it.gs
> +(#x1118 "ITALIANO")
Not needed.

2023-03-31 19:35 UTC, ManDude commented on game/assets/jak1/subtitle/game_subtitle_it.gd
> +  (16 "???" "GAH... EHI, GORDY! ACCIPICCHIA, PENSO CHE ABBIAMO DELLE VISITE!")
Willard and Gordy's names can be known before this plays, obscuring is unnecessary.

2023-03-31 19:35 UTC, ManDude commented on game/assets/jak1/subtitle/game_subtitle_it.gd
> +  (815 "???" "... NON È STATO AFFATTO DIVERTENTE.")
Make a distinction between Gol and Maia here.

2023-03-31 19:35 UTC, ManDude commented on game/assets/jak1/subtitle/game_subtitle_it.gd
> +  (946 "???" "PER IL RESTO LO ATTACCHEREMO A TEMPO DEBITO!")
Make a distinction between Gol and Maia here, otherwise you can't tell them apart.

2023-03-31 20:21 UTC, manuelx98 reviewed
It should be ok now?

2023-03-31 21:52 UTC, xTVaser commented
Are the changes complete?

2023-03-31 21:56 UTC, manuelx98 commented
> Are the changes complete?

Yep now, sorry. Had to add the new Speedrun section.

2023-03-31 22:34 UTC, merged