Pc port debug small qol
open-goal/jak-project pull request #1663
Opened 2022-07-16 17:27 UTC by Zedb0T

- Enable L2 'boost on racer if cheatmode **AND** PC_PORT
- Enable Daxter intro CS skip in title on retail mode if PC_PORT
- Fix typo to be consistent with other instances in code.
- Add empty jak1 folder in ISO_DATA (can revert this if need be)

2022-07-16 17:31 UTC, xTVaser requested changes
If you want to include the `jak1/` folder, you need to duplicate the `.gitignore` not move it, else there is the risk of other folders in `iso_data` being committed / unstaged.

2022-07-16 17:36 UTC, Zedb0T commented
I would need to add `!/jak1` 
So the * wildcard doesn't ignore the empty `jak1` directory correct?

2022-07-16 17:48 UTC, xTVaser commented
probably better to do a `!**/.gitignore`

2022-07-17 18:14 UTC, water111 approved these changes

2022-07-17 18:14 UTC, merged