game: add secrets menu, music player and some more pc settings
open-goal/jak-project pull request #1664
Opened 2022-07-16 17:47 UTC by Hat-Kid

Adds a secrets menu with PC cheats and a music player to the PC settings debug menu, as well as some missing PC settings like FPS, MSAA and V-Sync.

Also adds some string helper functions to the string library.

2022-07-16 22:12 UTC, ManDude requested changes
Thanks for adding this!

2022-07-16 22:12 UTC, ManDude commented on goal_src/jak1/engine/debug/default-menu.gc
> +                                                            (case (-> *pc-settings* gfx-msaa) ((16)))))
You can just do `(= (-> *pc-settings* gfx-msaa) 16)` etc here.

2022-07-16 22:12 UTC, ManDude commented on goal_src/jak1/engine/debug/default-menu.gc
> +                      (copy-string<-string (-> lvl-menu name) lvl)
Now you can do

```lisp
(let ((str (new 'debug 'string (- (length level-name) 11) #f))
  (set! (-> lvl-menu name) (copyn-string<-string str level-name (- (length level-name) 11)))
  )
```

2022-07-17 17:29 UTC, Hat-Kid commented
Figured out a much better way to deal with all the string manip stuff by making use of `*music-list*`.

2022-07-17 18:02 UTC, ManDude requested changes

2022-07-17 18:02 UTC, ManDude commented on goal_src/jak1/engine/debug/default-menu.gc
> +    )
You can use the `aif` macro here and save yourself the let. You can also just omit the check entirely, it's fine for `kill-by-name` not to find anything.

2022-07-17 18:02 UTC, ManDude commented on goal_src/jak1/kernel/gstring.gc
> +  "Copy len bytes of data from one string to another, like strcpy"
`strncpy`

2022-07-17 18:39 UTC, ManDude approved these changes
seems good to me right now!

2022-07-18 01:22 UTC, merged