d/jak2: finish `cylinder` | `mech-h` | `font-data` most of `text` and `history` and chip away at a bunch of other files
open-goal/jak-project pull request #1802
Opened 2022-08-25 04:43 UTC by xTVaser

- `level-info` has an issue with creating arrays of symbols from static data
- `text` has a CFG failure and the `print..` function seems to do something different, not sure if we manually fixed this one as it was never tested in jak 1's ref tests

2022-08-26 17:13 UTC, water111 requested changes

2022-08-26 17:13 UTC, water111 commented on goal_src/jak2/engine/debug/history.gc
> +  )
you could remove the inspects here if you want.

2022-08-26 17:13 UTC, water111 commented on goal_src/jak2/engine/debug/history.gc
> +    (let ((a1-3 (the-as history-elt (+ (+ (* 48 v1-0) 12) (the-as int obj)))))
Hm, this probably should be
```
(-> obj elts v1-0)
```
In the `history` deftype, it should probably be
```
(elts history-elt :dynamic :inline :offset 16)
```
might need a `:pack-me` on the `history-elt`, not sure.

2022-08-26 17:13 UTC, water111 commented on goal_src/jak2/engine/debug/history.gc
> +;; ERROR: function was not converted to expressions. Cannot decompile.
Looks like this one works if you remove it from `hacks.json`
Maybe
```
(history-method-asm-9 (_type_ int int int) object 9)
```

(with one of those ints being `history-channel`)

2022-08-26 17:13 UTC, water111 commented on goal_src/jak2/engine/debug/history.gc
> +        (let ((a2-5 (the-as history-elt (+ (+ (* 48 a2-1) 12) (the-as int v1-0)))))
this also should hopefully get cleaned up by making the `history-elt`s inline.

2022-08-26 17:13 UTC, water111 commented on goal_src/jak2/engine/level/level-h.gc
> +    (level-method-23 (_type_ game-text-id symbol) string 23)
Probably `lookup-text` or something like that.

2022-08-26 22:48 UTC, xTVaser commented on decompiler/config/jak2/anonymous_function_types.jsonc
> -  "level": [[5, "(function none)"]],
cleaning up duplicate json keys

2022-08-28 14:45 UTC, water111 approved these changes

2022-08-28 14:45 UTC, merged