add project path option to the compiler
open-goal/jak-project pull request #1826
Opened 2022-08-30 18:17 UTC by trippjoe

2022-09-02 02:11 UTC, xTVaser commented
add to whitelist

2022-09-16 00:51 UTC, trippjoe commented
Realized this isn't useful because we can just set the current working directory for goalc.

2022-09-18 12:47 UTC, trippjoe commented
Turns out I was wrong to close this.

2022-09-19 21:08 UTC, xTVaser requested changes
Tested with the suggested change made, works fine.  I was able to:
- open the REPL within the project folder with no args and build the game
- run the game
- move `goalc` to an entirely different folder on an entirely different drive, and have it work with the `--proj-path`:
![image](https://user-images.githubusercontent.com/13153231/191116723-2e1dcf27-b848-4684-b616-0a6b424bf50f.png)
![image](https://user-images.githubusercontent.com/13153231/191116828-5be4caba-2fec-45f4-82ea-b6d62e99de9a.png)

2022-09-19 21:08 UTC, xTVaser commented on goalc/main.cpp
> -  }
you can't get rid of this completely, this needs to still run if a project path is not provided, change it to an `else if` and add it after the condition you added below.  With that change, seems to work as expected
![image](https://user-images.githubusercontent.com/13153231/191116577-1773f89f-cbee-41a9-b1e8-f353ad56af88.png)

2022-09-24 00:49 UTC, xTVaser approved these changes
Did the same test as above, didn't have to make any code modifications this time -- looks good to me.

2022-09-24 16:06 UTC, water111 approved these changes
Thanks!

2022-09-24 16:06 UTC, merged