Reduced Default Graphics Settings
open-goal/jak-project pull request #1874
Opened 2022-09-12 22:58 UTC by himham-jak

Per https://discord.com/channels/756287461377703987/756287461830688810/1018649195927838830
I just turned on particle culling by default, set msaa to 1 and moved some values to constants up top for easy editing. Let me know if I made any mistakes.

2022-09-13 00:18 UTC, xTVaser requested changes
Seems like you've intermixed swedish subtitle changes in with this PR -- things will fail because the files it references doesn't exist, you should pull those changes out into a separate PR.

2022-09-13 00:20 UTC, xTVaser commented on goal_src/jak1/pc/pckernel-h.gc
> +  (set! (-> obj ps2-parts?) #t)
what does `ps2-parts?` do?

2022-09-13 00:21 UTC, ManDude commented on goal_src/jak1/pc/pckernel-h.gc
> +  (set! (-> obj ps2-parts?) #t)
yes

2022-09-13 00:37 UTC, xTVaser commented
Your experience for using git/github would be a lot better if you didn't do everything from the browser
- https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/overview/getting-started-with-github-desktop

2022-09-13 00:38 UTC, himham-jak commented
Ugh, github irks me. I'll comment out the swedish stuff

2022-09-13 00:38 UTC, himham-jak commented
I do have the desktop client. I need to use it more.

2022-09-13 00:39 UTC, xTVaser commented
Don't just comment it out, remove it entirely from the changeset.  The reason this is happening is because you aren't using a separate branch -- you're adding things to `master` (which is being used for this PR)

2022-09-13 00:51 UTC, himham-jak commented
> Don't just comment it out, remove it entirely from the changeset. The reason this is happening is because you aren't using a separate branch -- you're adding more things to `master` (which is being used for this PR)

should be fixed. my bad

2022-09-13 01:49 UTC, xTVaser commented
ok to test

2022-09-14 04:01 UTC, xTVaser approved these changes
Tested and seemed to work as expected -- I think it's better for the defaults to be conservative, though it's a little weird with the particle culling as everyone seems confused why it helps performance at all.

The new `defconstants` could probably be named a little better `DEFAULT_FRAME_RATE` instead of just `FRAME_RATE` for example but im not strongly opinionated on this.

2022-10-09 22:00 UTC, closed without merging