French subtitles
open-goal/jak-project pull request #2024
Opened 2022-11-16 19:42 UTC by 0xMisagi

## Cutscenes
- [x] intro
- [x] sidekick
- [x] oracle
- [x] village1
- [x] beach
- [x] jungle
- [x] misty
- [x] firecanyon
- [x] village2
- [x] swamp
- [x] village3
- [x] lavatube
- [x] citadel
- [x] finalboss

## Hints
- [x] sidekick
- [x] training
- [x] village1
- [x] beach
- [x] jungle
- [x] misty
- [x] firecanyon
- [x] village2
- [x] swamp
- [x] rolling
- [x] sunken
- [x] ogre
- [x] village3
- [x] snowy
- [x] spidercave
- [x] lavatube
- [x] citadel
- [x] finalboss
- [x] title

## Text
- [x] game_text_fr.gs

2022-11-16 20:14 UTC, ManDude requested changes

2022-11-16 20:14 UTC, ManDude commented on game/assets/jak1/text/game_text_en.gs
> +       "FRENCH")
Remove this.

2022-11-16 20:14 UTC, ManDude commented on game/assets/jak1/text/game_text_fr.gs
> +(#x115 "FRANÇAIS")
This line isn't necessary.

2022-11-16 20:19 UTC, 0xMisagi commented on game/assets/jak1/text/game_text_en.gs
> +       "FRENCH")
Done.

2022-11-16 23:36 UTC, ManDude approved these changes

2022-11-18 14:34 UTC, 0xMisagi commented
Ignore the commit ([9ab8732])

2022-11-20 00:07 UTC, 0xMisagi commented
Ready for offline tests. Let me know if there's any outliers (hopefully there shouldn't be)

subtitles are limited to 2 lines max on the default 4x3 resolution as told in the documentation

And game_text_fr.gs options menu entries are limited to a single line (manually checked)

2022-11-20 01:25 UTC, ManDude approved these changes

2022-11-22 23:27 UTC, xTVaser commented
ok to test

2022-11-26 23:49 UTC, merged