decompiler: some hacks to allow running decompiler on jak 3 v5 code files and generate `all-types`
open-goal/jak-project pull request #2526
Opened 2023-04-18 14:25 UTC by Hat-Kid

2023-04-22 01:27 UTC, ManDude requested changes

2023-04-22 01:27 UTC, ManDude commented on goal_src/jak2/engine/gfx/hw/display.gc
> +     )
Oops?

2023-04-22 01:28 UTC, Hat-Kid commented on goal_src/jak2/engine/gfx/hw/display.gc
> +     )
Whoops lol

2023-05-02 22:48 UTC, water111 approved these changes

2023-06-20 03:38 UTC, Hat-Kid commented
With the latest push, the `all-types` generation for Jak 3 has been vastly improved.

It should now pass most types without failing miserably except for two edge cases, `level-group`, which is so big that it stores its offsets for the load operations in separate registers and `load-dir` which is doing stack spill shenanigans. If it fails to read a field in the middle of an inspect, it will now just generate a dummy field instead of completely giving up on the type.

For far label types, it will now get the fields, but will still fail to get the flags and, sometimes, the parent type, which is still a vast improvement over nothing.

2023-07-06 15:11 UTC, ManDude submitted a review, later dismissed

2023-07-06 15:11 UTC, ManDude commented on goal_src/jak3/build/all_objs.json
> +["tomb-baby-spider-TEMA",                           "tomb-baby-spider",                                5, ["TEMA"], ""],
We still need to do something about this - can you detect if the type of a data-only object file is a child of (or exactly) `art-group`?

2023-10-07 20:14 UTC, merged