jak2: add `.gd` files and level info for some ps3 test levels
open-goal/jak-project pull request #2776
Opened 2023-06-26 01:57 UTC by Hat-Kid

Adds some of the internal test levels that can be found in the PS3 version of Jak 2 to `game.gp`.
DGOs are not provided.

Disabled and commented out by default, can be toggled with the `USE_PS3_LEVELS` flag and by uncommenting the DGOs in `inputs.jsonc`.

Also comes with a script to generate the `*.DGO.txt` file for a DGO folder for use with the `dgo_packer`.

2023-06-26 17:01 UTC, LuminarLight commented
Hello, I checked the list, and it seems you missed 'stadocc' (a tiny black cube) and 'ctyfence' (a giant very early outline of the city - very cool stuff). I have videos of both, but it would probably be unnecessary/inappropriate to post them here.

2023-06-26 20:16 UTC, ManDude requested changes

2023-06-26 20:16 UTC, ManDude commented on goal_src/jak2/engine/level/level-info.gc
> +        :vis-nick 'dptest
Can you mark these and other lines you altered?

2023-06-27 09:28 UTC, ManDude approved these changes

2023-06-27 21:52 UTC, merged