jak2: add missing pc options to progress menu
open-goal/jak-project pull request #3167
Opened 2023-11-06 03:17 UTC by Hat-Kid

Adds the majority of the missing PC options to the progress menu, such as most of the graphics options, camera options and a quit game button on the title screen menu.
![image](https://github.com/open-goal/jak-project/assets/6624576/8d14a24d-257b-4d72-a88d-95b90f7691ed)
![image](https://github.com/open-goal/jak-project/assets/6624576/75306ae2-8044-4507-a471-e7cdb6245dab)

2023-11-06 11:57 UTC, ManDude requested changes

2023-11-06 11:57 UTC, ManDude commented on goal_src/jak2/pc/progress/progress-static-pc.gc
> +          (commit-to-file *pc-settings*)))
Do not add this option. It's not a good idea for Jak 2.

2023-11-06 11:57 UTC, ManDude commented on goal_src/jak2/pc/progress/progress-static-pc.gc
> +          (commit-to-file *pc-settings*)))
Don't add this one either.

2023-11-06 22:05 UTC, ManDude requested changes

2023-11-06 22:05 UTC, ManDude commented on goal_src/jak2/pc/progress/progress-static-pc.gc
> +            (commit-to-file *pc-settings*))))))
Can you actually move these to only show up for game options in the title screen? I don't want to deal with potential bugs of changing this mid-elevator and stuff (not that I believe there are any, but yeah).

2023-11-08 22:54 UTC, xTVaser approved these changes
Pulled it down and tested the major things -- if graphics options save / if the camera changes work.  They did

2023-11-09 16:21 UTC, ManDude approved these changes

2023-11-09 16:24 UTC, merged