Add auto cutscene skip option
open-goal/jak-project pull request #3186
Opened 2023-11-11 08:32 UTC by Zedb0T

Disabled by default but if enabled automatically skip cutscenes when possible.
Setting is shared between jak 1 and jak 2

Tested flutflut cutscene
Tested cell buying cutscenes
Tested final boss
Tested rats/fisherman
Tested failing rats/fisherman
Tested misty boat
Tested jak 2 onin game
Tested jak 2 mission fail
Tested jak 2 final boss

https://github.com/open-goal/jak-project/assets/89345505/245c6cde-7015-48f9-9ac7-e962ce0c4db8

2023-11-11 11:10 UTC, ManDude requested changes

2023-11-11 11:10 UTC, ManDude commented on goal_src/jak1/engine/common-obs/process-taskable.gc
> +          )
wrong indenting

2023-12-26 23:49 UTC, Zedb0T commented
If we are resetting the settings anyways, should we also look to merge #3275  at the same time?

2023-12-30 19:40 UTC, Zedb0T commented
Merge master and afaik this should be ready for a review.

2024-02-23 23:53 UTC, xTVaser commented
Cleaning up stale PRs - this PR has sat for a while with feedback and no movement, re-open if/when work resumes.

2024-02-24 19:43 UTC, Zedb0T commented
I changed the menu to the updated Jak 2 format sorry wasn't aware that the standard for that changed while this PR was waiting/sitting. Outside of that I really wasn't aware of anything that need ed to be done with this PR? If there was something please feel to advise. 

There was a Lint failure on the original PR but it was just a very very intentional change to the text of a og::preserve and the linter was mistaken in thinking that I was removing it.

2024-02-25 00:06 UTC, Zedb0T commented
Discovered a bug on this, Just documenting it real quick it wasnt observed before the work on 2/24 so it shouldn't take too long to fix, rest of the code is being retested now but assumed to be good 😢


https://github.com/open-goal/jak-project/assets/89345505/a9d6cfca-5523-437d-8edc-c74e1f1a13ce

2024-02-25 01:39 UTC, Hat-Kid commented
This is not a bug caused by your changes, this happens on `master` as well and appears to be related to the new joint decompression code added in #3369 as using the old decompressor fixes it.

2024-03-03 21:16 UTC, xTVaser commented
With https://github.com/open-goal/jak-project/pull/3394 merging, does the bug go away?

2024-03-03 21:40 UTC, Zedb0T commented
Ill merge and test in 2/3 hours

2024-03-04 02:31 UTC, Zedb0T commented
I can confirm the bug no longer occurs but I am trying to clean one more thing up but dont want to miss the release deadline :( any idea when it will be? 

Not trying to push but I just want this merged, it feels like a diff game with it on its so nice.

2024-03-04 02:35 UTC, Zedb0T commented
https://github.com/open-goal/jak-project/assets/89345505/4303b496-2386-4ecb-a424-1c65ac812d02

I want fish and rats game to autostart when talking to these people as you would expect if their cutscenes are skipped then maintain the Play again yes/no menu if you lose/quit out.

I was so certain I had this working but I guess not or I didnt push it, cant see it in the git history anywhere

2024-03-04 02:37 UTC, xTVaser commented
> I can confirm the bug no longer occurs but I am trying to clean one more thing up but dont want to miss the release deadline :( any idea when it will be?

It will be in next month's release.  The next release will be in the next day or so and it's best to avoid rush merging something in.

2024-04-14 19:10 UTC, xTVaser commented
Re-open if you eventually fix the issue you mentioned here and it's ready to merge https://github.com/open-goal/jak-project/pull/3186#issuecomment-1975548971 It doesn't feel like this is ready or a top priority.

2024-04-14 19:10 UTC, closed without merging