Add jak 2 all open orbs speedrun category
open-goal/jak-project pull request #3195
Opened 2023-11-12 01:51 UTC by Zedb0T

2023-11-12 01:53 UTC, xTVaser commented on goal_src/jak2/pc/features/speedruns.gc
> +      (set-master-mode 'game)
hiding the menu here shouldn't be required, none of the other categories require that?  The menu automatically hides when hitting "reset".  I believe that should also change the master-mode as well.

2023-11-12 01:59 UTC, xTVaser commented on goal_src/jak2/pc/features/speedruns.gc
> +      (set-master-mode 'game)
Ah I understand, kk well as long as it works then maybe it can be cleaned up later.

2023-12-02 20:11 UTC, xTVaser requested changes
This has a problem, the run info isn't displayed because right now it is controlled by fortress escape being completed (since you start in the nest with tasks unlocked, its immediately hidden).  We should break out that criteria into a separate function on a per-category basis.

2024-01-09 19:45 UTC, Zedb0T commented
> This has a problem, the run/verification info isn't displayed because right now it is controlled by fortress escape being completed (since you start in the nest with tasks unlocked, its immediately hidden). We should break out that criteria into a separate function on a per-category basis.
You fine with me birthing a process that displays the info for the first 15 seconds of the run instead?

2024-02-23 23:53 UTC, closed without merging

2024-02-23 23:53 UTC, xTVaser commented
Cleaning up stale PRs - this PR has sat for a while with feedback and no movement, re-open if/when work resumes.