decomp3: Some code files
open-goal/jak-project pull request #3499
Opened 2024-05-01 07:41 UTC by Nick0778

I decompiled some more code files. I'm just not sure about `rublcst-scenes`, but the rest is probably working fine. 
- `combx-obs`
- `lfaccity-mood`
- `wlander-h`
- `rubblea-init`
- `hover-nav-lpattack`
- `rublcst-scenes`
- `rubble-part`

2024-05-01 11:01 UTC, Hat-Kid requested changes

2024-05-01 13:41 UTC, Nick0778 commented on decompiler/config/jak3/all-types.gc
> -   (anim-knocked-back-land  int32     :offset-assert 20)
Fine! So, no need to change the offset values, right?! Is it only necessary to add `offset` instead of `offset-assert`?

2024-05-01 14:06 UTC, Hat-Kid commented on decompiler/config/jak3/all-types.gc
> -   (anim-knocked-back-land  int32     :offset-assert 20)
Yes.

2024-05-01 14:12 UTC, Nick0778 commented on decompiler/config/jak3/all-types.gc
> +(define-extern lfaccity-pparticle-mover-init-by-other (function vector quaternion vector float object :behavior lfaccity-pparticle-mover))
Okay! it should be `(define-extern lfaccity-pparticle-mover-init-by-other (function entity-actor :behavior lfaccity-pparticle-mover))`?

2024-05-01 14:52 UTC, Hat-Kid commented on decompiler/config/jak3/all-types.gc
> +(define-extern lfaccity-pparticle-mover-init-by-other (function vector quaternion vector float object :behavior lfaccity-pparticle-mover))
No, it would be `(function entity-actor object :behavior lfaccity-pparticle-mover)` because it returns `object`.

2024-05-01 17:39 UTC, Nick0778 commented on decompiler/config/jak3/all-types.gc
> +  ((actor-group       uint32  :offset-assert 200)
Yeah, I did what you said and I'm getting a error saying: `Field actor-group was placed at 200 but offset-assert was set to 196`

So, what I did looks like this: 
`((actor-group       (pointer actor-group) :offset-assert 196)`
     `(actor-group-count int32   :offset-assert 200)`
      `(particles         faccity-pparticle-array   :offset-assert 204)`

2024-05-01 17:42 UTC, Hat-Kid commented on decompiler/config/jak3/all-types.gc
> +  ((actor-group       uint32  :offset-assert 200)
Changing those offsets was actually correct in this one instance, this is from a bug in the `all-types` generation where the offsets of some `process` types are off by 4.

2024-05-01 18:17 UTC, Nick0778 commented on decompiler/config/jak3/ntsc_v1/type_casts.jsonc
> +  ],
So, to fix those bad casts, should I have to change `(lfaccity-pparticle-mover-method-21 (_type_) none) ;; 21` types?

2024-05-01 18:18 UTC, Hat-Kid commented on decompiler/config/jak3/ntsc_v1/type_casts.jsonc
> +  ],
The type `lfaccity-pparticle-mover`, not the method.

2024-05-01 20:17 UTC, Nick0778 commented on decompiler/config/jak3/all-types.gc
> +(define-extern *faccity-part-updater* object)
So, in this case, it should be `(define-extern *faccity-part-updater* lfaccity-pparticle-mover)`?

2024-05-01 20:18 UTC, Hat-Kid commented on decompiler/config/jak3/all-types.gc
> +(define-extern *faccity-part-updater* object)
Yes.

2024-05-01 20:51 UTC, Nick0778 commented on goal_src/jak3/levels/comb/combx-obs.gc
> +    (combx-elevator-method-22 (_type_) none) ;; I couldn't decompile it, but I don't think it's necessary.
![png1](https://github.com/open-goal/jak-project/assets/149975116/bdeb9207-93da-447c-bd67-0942f786ad2d)
![png2](https://github.com/open-goal/jak-project/assets/149975116/6a01dd8a-5c59-464f-a652-7cf42775068e)

I'm stucked here to figure out what was supposed this `method 46` of type `trsqv` that the decompiler is reffering to. Is there something related to `draw-control` or something?

2024-05-01 21:43 UTC, Hat-Kid commented on goal_src/jak3/levels/comb/combx-obs.gc
> +    (combx-elevator-method-22 (_type_) none) ;; I couldn't decompile it, but I don't think it's necessary.
`combx-elevator` is a `process-drawable`, which has a `trsqv` at offset 128. However, `trsqv` does not have a method 46, so they are actually putting something else at that spot. In this case, it's a `collide-shape-moving`, as seen by how it initializes the collision in `combx-elevator::21`. So, you can either cast that or add it as an override field.

2024-05-01 22:41 UTC, Nick0778 commented
All good! I fixed pretty much all the things you said! Do I need to do anything else?

2024-05-31 01:49 UTC, xTVaser commented
This has a lot of conflicts and is apparently obsoleted (the files have been decompiled already in master, likely the reason for the conflicts)

2024-05-31 01:49 UTC, closed without merging