[jak2] new subtitle speakers
open-goal/jak-project pull request #3536
Opened 2024-05-25 18:39 UTC by Aloqas

for specific cutscene scenarios

2024-05-25 19:42 UTC, ManDude requested changes

2024-05-25 19:42 UTC, ManDude commented on goal_src/jak2/pc/subtitle2-h.gc
> +
use `set-subtitle-speaker-color<-speaker!` here

2024-05-25 21:12 UTC, ManDude approved these changes

2024-05-31 01:47 UTC, xTVaser commented
ok to test

2024-05-31 02:02 UTC, merged