Fix github release-pipeline so version tag is available for cmake
open-goal/jak-project pull request #3651
Opened 2024-09-03 20:38 UTC by dallmeyer

Followup to https://discord.com/channels/756287461377703987/1280601431975661599 where v0.2.16 release is showing git SHA instead of the version tag

2024-09-04 01:15 UTC, xTVaser requested changes

2024-09-04 01:15 UTC, xTVaser commented on .github/workflows/linux-build-clang.yaml
> +          fetch-tags: true
doing a full checkout adds ~10s to this step comparing to older runs.  

I think we should add it to it's own step, ie. `Checkout Repository with Tags` that has an `if: ${{ inputs.uploadArtifacts }}` and then this step can have an `if: !${{ inputs.uploadArtifacts }}`.  This is so it only runs when it is required on a release workflow.

2024-09-05 06:43 UTC, xTVaser commented on .github/workflows/release-pipeline.yaml
> +      - cut-release
s/cut-release/cut_release

2024-09-05 06:44 UTC, dallmeyer commented on .github/workflows/release-pipeline.yaml
> +      - cut-release
ah good catch

2024-09-10 03:26 UTC, xTVaser approved these changes

2024-09-10 03:26 UTC, merged